default["mongodb"]["docker_image"] = "kjunine/mongodb"
default["mongodb"]["docker_image_tag"] = "latest"
default["mongodb"]["docker_container"] = "mongod"
default["mongodb"]["data_path"] = "/data"
default["mongodb"]["replset"] = "test"
default["mongodb"]["server"]["address"] = "localhost:27017"
